#!/bin/bash

function __show_tasks {
        compgen -A function | grep -v "^_"
}

function start {
        docker-compose -p pwnycodetest up -d
}

function stop {
        docker-compose -p pwnycodetest down
}

function help {
        echo "$0 <task> <args>"
        echo "Tasks:"
        tasks | cat -n
}

function tasks {
        compgen -A function
}

function default {
        tasks
}

"${@:-default}"

